### ISSUE TITLE
error  'console' is not defined

### ISSUE THREAD

**Issue by nuovecode** [bengrunfeld/expack#4]
Hi Ben,  your boilerplate works fine! thanks for sharing.
I'm receiving this error during the dev build (seems to me doesn't compromise the funcrioning):
```
.../src/js/logger.js
1:27  error  Unexpected console statement  no-console
1:27  error  'console' is not defined
```

**Comment by bengrunfeld** [comment]
Glad to hear that you like it!
Yes, this error is being generated by ESLint and is expected behavior. If you want to suppress this error in the linter, you can use `// eslint-disable-line no-undef` on the same line as the console log statement. Otherwise, you can just change the code the not use a `console.log` statement. Best if you read up about linting though, since it's a powerful tool that can really help you write better code. 
Have a great day!! 😁
